### PR TITLE
added-back-top-button

### PR DESCRIPTION
**Pull request by suleimanbashiru**

### CODE REVIEW

**Comment by suleimanbashiru** [comment]
Done

**Comment by jyarali** [comment]
Please organize your code.
javascripts should be in scripts.js
styles in style.css file
jQuery is already loaded in page, you loaded it twice.
font awesome is not needed.
I'm closing this pull request.
please solve the problems mentioned (if you are interested) and make another pull request.

**Comment by suleimanbashiru** [comment]
Done

**Comment by jyarali** [comment]
> Done

jQuery is already loaded in page, you loaded it twice.
pay attention to smooth scrolling, something like: https://codepen.io/chriscoyier/pen/dpBMVP/
Make a new PR for your next commits.

**Pull request closed without merging**
