### PR TITLE
further improving smooth scroll

### PR DESCRIPTION
**Pull request by iakshat**
solving #12 
don't know why there is conflict please look into that and let me know how can i improve

### CODE REVIEW

**Comment by iakshat** [comment]
Ohh got that!

**Comment by jyarali** [comment]
Did you test your code after commits?
Can you see back to top button in the page?

**Comment by iakshat** [comment]
Yes that was working fine

**Comment by jyarali** [comment]
Please check again, there is no button on page!
you've removed go to top button and css styles related to it.

**Comment by iakshat** [comment]
I think I got it this time

**Comment by jyarali** [comment]
well done.

**Pull request merged**
